build:
  tags:
    - wsl
  stage: build
  before_script:
    #- sudo apt-get update --yes
    #- sudo apt-get install --yes cmake
  script:
    - echo "building..."
    - mkdir build
    - cd build
    - 'test -s ~/.alias && . ~/.alias || true'
    - # add default lib paths
    - 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib'
    - /usr/local/bin/cmake/bin/cmake ..
    - /usr/local/bin/cmake/bin/cmake --build .
    - ls

test:
  tags:
    - wsl
  stage: test
  before_script:
    #- sudo apt-get update --yes
    #- sudo apt-get install --yes cmake
  script:
    - echo "testing..."
    - cd $CI_PROJECT_DIR/src/peridigmVsBuild/src/materials/unit_test
    - /usr/local/bin/cmake/bin/ctest -T Test
    - xsltproc $CI_PROJECT_DIR/src/peridigmSource/scripts/CTest2JUnit.xsl Testing/`head -n 1 < Testing/TAG`/Test.xml > JUnitTestResults.xml
    #- cp /usr/local/src/peridigmVsBuild/src/materials/unit_test/JUnitTestResults.xml JUnitTestResults.xml
    - echo $CI_PROJECT_DIR
  artifacts:
    when: always
    reports:
      junit: /src/peridigmVsBuild/src/materials/unit_test/JUnitTestResults.xml

