job:
  tags:
    - wsl
  stage: test
  before_script:
    #- sudo apt-get update --yes
    #- sudo apt-get install --yes cmake
  script:
    - cd /usr/local/src/peridigmVsBuild/src/materials/unit_test
    - /usr/local/bin/cmake/bin/ctest -T Test
    - xsltproc /usr/local/src/peridigmSource/scripts/CTest2JUnit.xsl Testing/`head -n 1 < Testing/TAG`/Test.xml > JUnitTestResults.xml
    - ls -al
  artifacts:
    when: always
    reports:
      junit: /usr/local/src/peridigmVsBuild/src/materials/unit_test/JUnitTestResults.xml

