build:
  tags:
    - wsl
  stage: build
  before_script:
    #- add cmake
    - echo $PATH
  script:
    - echo "building..."
    - mkdir build
    - cd build
    - echo $CI_PROJECT_DIR
    - cmake .. -D CMAKE_BUILD_TYPE:STRING=Release
      -D Trilinos_DIR:PATH=/usr/local/bin/trilinos/lib/cmake/Trilinos/
      -D CMAKE_C_COMPILER:STRING=/usr/local/lib/openmpi/bin/mpicc
      -D CMAKE_CXX_COMPILER:STRING=/usr/local/lib/openmpi/bin/mpicxx
      -D BOOST_ROOT=/usr/local/lib/boost/
      -D CMAKE_CXX_FLAGS:STRING="-O2 -Wall -std=c++11 -pedantic -Wno-long-long -ftrapv -Wno-deprecated"
    - cmake --build .
    - ls
  artifacts:
    paths:
        - build
    expire_in: 30 mins

test:
  tags:
    - wsl
  stage: test
  before_script:
    - echo "testing..."
    - cd $CI_PROJECT_DIR/build
    - /usr/local/bin/cmake/bin/ctest -T Test
  script:
    - ls
    - xsltproc $CI_PROJECT_DIR/scripts/CTest2JUnit.xsl Testing/`head -n 1 < Testing/TAG`/Test.xml > JUnitTestResults.xml
    #- cp /usr/local/src/peridigmVsBuild/src/materials/unit_test/JUnitTestResults.xml JUnitTestResults.xml
    - echo $CI_PROJECT_DIR
  artifacts:
    when: always
    reports:
      junit: build/JUnitTestResults.xml

