job:
  tags:
    - wsl
  before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
  script:
    - cd /usr/local/src/peridigmVsBuild/src/materials/unit_test
    - ctest -T Test
    - xsltproc /usr/local/src/peridigmSource/scripts/CTest2JUnit.xsl Testing/`head -n 1 < Testing/TAG`/Test.xml > JUnitTestResults.xml

