build:
  tags:
    - wsl
  stage: build
  before_script:
    #- sudo apt-get update --yes
    #- sudo apt-get install --yes cmake
  script:
    - echo "building..."
    - mkdir build
    - cd build
    - 'test -s ~/.alias && . ~/.alias || true'
    - # add default lib paths
    - |
      'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib'
      'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64'
      'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib'
      'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64'
      # add cmake
      'export PATH=$PATH:/usr/local/bin/cmake/bin'
      # add openMPI
      'export PATH=$PATH:/usr/local/lib/openmpi/bin'
      'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/openmpi/lib64'
      # add boost
      'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/boost/lib'
      # add hdf5
      'export PATH=$PATH:/usr/local/bin/hdf5/bin'
      'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/bin/hdf5/lib'
      # add netcdf
      'export PATH=$PATH:/usr/local/bin/netcdf/bin'
      'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/bin/netcdf/lib64'
      # add trilinos
      'export PATH=$PATH:/usr/local/bin/trilinos/bin'
      'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/bin/trilinos/lib'
    - /usr/local/bin/cmake/bin/cmake ..
    - /usr/local/bin/cmake/bin/cmake --build .
    - ls

test:
  tags:
    - wsl
  stage: test
  before_script:
    #- sudo apt-get update --yes
    #- sudo apt-get install --yes cmake
  script:
    - echo "testing..."
    - cd $CI_PROJECT_DIR/src/peridigmVsBuild/src/materials/unit_test
    - /usr/local/bin/cmake/bin/ctest -T Test
    - xsltproc $CI_PROJECT_DIR/src/peridigmSource/scripts/CTest2JUnit.xsl Testing/`head -n 1 < Testing/TAG`/Test.xml > JUnitTestResults.xml
    #- cp /usr/local/src/peridigmVsBuild/src/materials/unit_test/JUnitTestResults.xml JUnitTestResults.xml
    - echo $CI_PROJECT_DIR
  artifacts:
    when: always
    reports:
      junit: /src/peridigmVsBuild/src/materials/unit_test/JUnitTestResults.xml

